name: 'eksctl'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  eksctl:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # Use python virtual environment for specific awscli version
    - name: Set Up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Enable Pip Cache
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Pip Install Dependencies
      run: |
        python --version
        pip install -r requirements.txt
      - name: Install eksctl 0.11.1
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/0.11.1/eksctl_Linux_amd64.tar.gz" | tar xz -C ./
          ./eksctl version
      - name: Install helm 3.0.2
        run: |
          curl --silent --location "https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz" | tar xz -C ./
          ./linux-amd64/helm version
      - name: Add Runner IP to Kubernetes API Whitelist
        run: |
          RUNNERIP=`curl --silent http://checkip.amazonaws.com`
          aws eks update-cluster-config --name pangeo --resources-vpc-config publicAccessCidrs=$RUNNERIP/32
          # better to poll for readiness https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html
          sleep 30
      - name: Get info on running pods
        run: |
          kubectl get pods --all-namespaces
      - name: Remove runner IP from Kubernetes API Whitelist
        run: |
          # need to keep at least 1 IP in list
          aws eks update-cluster-config --name pangeo --resources-vpc-config publicAccessCidrs="174.21.142.69/32"
