name: 'EKSCTL'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  eksctl:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: Get IP Address
        run: |
          RUNNERIP=`curl --silent http://checkip.amazonaws.com`
          echo $RUNNERIP
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_linux_amd64.tar.gz" | tar xz -C ./
          ./eksctl version
      - name: Install helm3
        run: |
          curl --silent --location "https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz" | tar xz -C ./
          ./linux-amd64/helm version
